# ml/gen_raw_tree_go.py
"""
Generate internal/service/raw_tree.go from ml/models/raw_tree.pkl.

The tree is trained on the 14-dim normalized vectors from references.json.gz.
At inference time, the same 14 dims are available from Vec.Vectorize() (the first
14 elements of the 16-dim output). RawTreePredict therefore accepts [16]float32.

Usage:
    uv run --with numpy --with scikit-learn ml/gen_raw_tree_go.py
"""
import pickle
from pathlib import Path


def main():
    root = Path(__file__).parent.parent
    src = root / "ml" / "models" / "raw_tree.pkl"
    dst = root / "internal" / "service" / "raw_tree.go"

    with open(src, "rb") as f:
        m = pickle.load(f)

    n = m["n_nodes"]
    left = m["children_left"]
    right = m["children_right"]
    feature = m["feature"]
    threshold = m["threshold"]
    confident = m["confident"]
    leaf_class = m["leaf_class"]
    n_features = m.get("n_features", 14)

    conf_count = sum(confident)
    print(f"Generating raw_tree.go: {n} nodes, {conf_count} confident leaves, {n_features} features")

    lines = []
    lines.append("package service")
    lines.append("")
    lines.append("// Code generated by ml/gen_raw_tree_go.py — DO NOT EDIT.")
    lines.append(f"// Nodes: {n}, Confident leaves: {conf_count}")
    lines.append(f"// Confidence threshold: {m['confidence_threshold']}")
    lines.append(f"// Trained on {n_features}-dim normalized vectors from references.json.gz")
    lines.append("")

    def fmt_int32(name, values):
        body = ", ".join(str(v) for v in values)
        return f"var {name} = [{n}]int32{{{body}}}"

    def fmt_int8(name, values):
        body = ", ".join(str(v) for v in values)
        return f"var {name} = [{n}]int8{{{body}}}"

    def fmt_float32(name, values):
        body = ", ".join(f"{v:.9f}" for v in values)
        return f"var {name} = [{n}]float32{{{body}}}"

    def fmt_bool(name, values):
        body = ", ".join("true" if v else "false" for v in values)
        return f"var {name} = [{n}]bool{{{body}}}"

    lines.append(fmt_int32("rtLeft", left))
    lines.append(fmt_int32("rtRight", right))
    lines.append(fmt_int8("rtFeature", feature))
    lines.append(fmt_float32("rtThreshold", threshold))
    lines.append(fmt_bool("rtConfident", confident))
    lines.append(fmt_int8("rtClass", leaf_class))
    lines.append("")
    lines.append("// RawTreePredict classifies a normalized feature vector using the pre-trained decision tree.")
    lines.append("// vec is the 16-dim output of Vec.Vectorize(); only the first 14 dims are used (matching")
    lines.append("// the training data from references.json.gz).")
    lines.append("// Returns (fraudCount, true) only when the reached leaf is confident")
    lines.append("// (majority class >= confidence threshold during training).")
    lines.append("// Returns (0, false) for uncertain leaves — caller should fall through to k-NN.")
    lines.append("func RawTreePredict(vec [16]float32) (int, bool) {")
    lines.append("\tnode := int32(0)")
    lines.append("\tfor rtLeft[node] != -1 {")
    lines.append("\t\tif vec[rtFeature[node]] <= rtThreshold[node] {")
    lines.append("\t\t\tnode = rtLeft[node]")
    lines.append("\t\t} else {")
    lines.append("\t\t\tnode = rtRight[node]")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\tif !rtConfident[node] {")
    lines.append("\t\treturn 0, false")
    lines.append("\t}")
    lines.append("\tif rtClass[node] == 1 {")
    lines.append("\t\treturn 5, true")
    lines.append("\t}")
    lines.append("\treturn 0, true")
    lines.append("}")
    lines.append("")

    dst.write_text("\n".join(lines))
    print(f"Written {dst} ({dst.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
