# ml/gen_tree_go.py
"""
Generate internal/search/decision_tree.go from ml/decision_tree_model.json.

Usage:
    uv run ml/gen_tree_go.py
"""
import json
from pathlib import Path


def main():
    root = Path(__file__).parent.parent
    src = root / "ml" / "decision_tree_model.json"
    dst = root / "internal" / "search" / "decision_tree.go"

    with open(src) as f:
        m = json.load(f)

    n = m["n_nodes"]
    left = m["children_left"]
    right = m["children_right"]
    feature = m["feature"]
    threshold = m["threshold"]
    confident = m["confident"]
    leaf_class = m["leaf_class"]

    conf_count = sum(confident)
    print(f"Generating tree: {n} nodes, {conf_count} confident leaves")

    lines = []
    lines.append("package search")
    lines.append("")
    lines.append("// Code generated by ml/gen_tree_go.py — DO NOT EDIT.")
    lines.append(f"// Nodes: {n}, Confident leaves: {conf_count}")
    lines.append("")

    def fmt_int32_arr(name, values):
        body = ", ".join(str(v) for v in values)
        return f"var {name} = [{n}]int32{{{body}}}"

    def fmt_int8_arr(name, values):
        body = ", ".join(str(v) for v in values)
        return f"var {name} = [{n}]int8{{{body}}}"

    def fmt_float32_arr(name, values):
        body = ", ".join(f"{v:.9f}" for v in values)
        return f"var {name} = [{n}]float32{{{body}}}"

    def fmt_bool_arr(name, values):
        body = ", ".join("true" if v else "false" for v in values)
        return f"var {name} = [{n}]bool{{{body}}}"

    lines.append(fmt_int32_arr("dtLeft", left))
    lines.append(fmt_int32_arr("dtRight", right))
    lines.append(fmt_int8_arr("dtFeature", feature))
    lines.append(fmt_float32_arr("dtThreshold", threshold))
    lines.append(fmt_bool_arr("dtConfident", confident))
    lines.append(fmt_int8_arr("dtClass", leaf_class))
    lines.append("")
    lines.append("// DecisionTree classifies vec using the pre-trained fraud decision tree.")
    lines.append("// Returns (fraudCount, true) only when the reached leaf is confident")
    lines.append("// (majority class >= confidence threshold during training).")
    lines.append("// Returns (0, false) for uncertain leaves — caller should fall through to k-NN.")
    lines.append("func DecisionTree(vec [14]float32) (int, bool) {")
    lines.append("\tnode := int32(0)")
    lines.append("\tfor dtLeft[node] != -1 {")
    lines.append("\t\tif vec[dtFeature[node]] <= dtThreshold[node] {")
    lines.append("\t\t\tnode = dtLeft[node]")
    lines.append("\t\t} else {")
    lines.append("\t\t\tnode = dtRight[node]")
    lines.append("\t\t}")
    lines.append("\t}")
    lines.append("\tif !dtConfident[node] {")
    lines.append("\t\treturn 0, false")
    lines.append("\t}")
    lines.append("\tif dtClass[node] == 1 {")
    lines.append("\t\treturn 5, true")
    lines.append("\t}")
    lines.append("\treturn 0, true")
    lines.append("}")
    lines.append("")

    dst.write_text("\n".join(lines))
    size_kb = dst.stat().st_size // 1024
    print(f"Written {dst} ({size_kb} KB)")


if __name__ == "__main__":
    main()
