FROM golang:1.26.3 AS builder

WORKDIR /app

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOAMD64=v3

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/lb/ ./cmd/lb/

RUN go build \
    -trimpath \
    -buildvcs=false \
    -ldflags="-s -w" \
    -o lb \
    ./cmd/lb

FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/lb /lb
ENTRYPOINT ["/lb"]
